### PR TITLE
Fix topaxis bottomhover rangeofthres

### PR DESCRIPTION
**Pull request by lebronlambert**
fix run TreeLasso problem 
fix load file
fix createcount
fix readme
fix comment things
fix dead algorithms

### CODE REVIEW

**Comment by blengerich** [comment]
Can one of the admins verify this patch?

**Comment by lebronlambert** [comment]
we need to merge the new changes for treelasso.cpp

**Comment by blengerich** [comment]
@lebronlambert do you mean that the treelasso.cpp changes should be merged before this PR? Or the other way around?

**Comment by lebronlambert** [comment]
Just fine. You can merge it before this PR or after this PR. I just fix this bug together with Haohan and he said  I should merge it, too.

**Pull request merged**
