### PR TITLE
[new] Install some packages & change JacobiSVD to BCDSVD

### PR DESCRIPTION
**Pull request by YeWenting**
Installed packages:
Eigen 3.3.4
MongoDB C++11 Driver 3.1.2
libplinkio

To add package above, the following packages are also installed:
libbson-1.0-0_1.3.1-1_amd64
libmongoc-1.0-0_1.3.1-1_amd64
mongo-c-driver-1.6.3

Edit "Model_test.cpp" just to make it right... (I have discussed this with Haohan)
Some details are also added in README.
btw, I still cannot push the images in Docker since the lack of access:)

### CODE REVIEW

**Comment by blengerich** [comment]
Can one of the admins verify this patch?

**Comment by YeWenting** [comment]
Pushed to the blengerich/genamap:new_environment

**Comment by YeWenting** [comment]
Pushed to the blengerich/genamap:new_environment in Docker

**Comment by blengerich** [comment]
LGTM. @YeWenting, do you have access to push Docker to blengerich/genamap:latest? If so, do that and it will download when pulling blengerich/genamap Docker.

**Comment by YeWenting** [comment]
Ok, I pushed it in a different tag. I will push to "Latest" today asap:)

**Comment by YeWenting** [comment]
still cannot merge :(

**Comment by blengerich** [comment]
@YeWenting, the merge is blocked by the CI because I hadn't added you to the CI's approved submitters whitelist at the time of this PR (hence the message from jenkins: "Can one of the admins verify this patch?"). I will merge this PR since it is minor changes, and your next PR should have CI build automatically.

**Pull request merged**
